title: RC timing theory
hero_image: images/banner.png
description: How RC timing circuits work
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "electronics"
steps:
  - title: RC timing theory


